data_collection:
  additional_envs:
  - FogTrain
  - RandomTrain
  env: NormalTrain
  episodes: 200
  output_dir: ./dataset_mouse_dino
  steps_per_episode: 500
  train_val_split: true
finetuning:
  architectures:
  - dino_encoder
  max_steps: 50000
  output_dir: ./dino_rl_results
  runs_per_network: 3
  unfreeze_layers: 2
pretraining:
  batch_size: 64
  epochs: 50
  model:
    depth: 6
    embed_dim: 384
    img_size: 224
    num_heads: 6
    patch_size: 16
  output_dir: ./dino_checkpoints
  use_wandb: false
