# behaviors:
#   My Behavior:
#     trainer_type: ppo
#     hyperparameters:
#       batch_size: 128
#       buffer_size: 2048
#       learning_rate: 0.0003
#       beta: 0.005
#       epsilon: 0.2
#       lambd: 0.95
#       num_epoch: 3
#       learning_rate_schedule: linear
#     network_settings:
#       normalize: false
#       hidden_units: 256
#       num_layers: 2
#       vis_encode_type: nature_cnn
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0
#     checkpoint_interval: 5000
#     keep_checkpoints: 10
#     max_steps: 20000
#     summary_freq: 2000
#     threaded: true



behaviors:
  My Behavior:
    # init_path: "results/resnet_with_augmentation_RandomTrain_3/My Behavior/My Behavior-231517.pt"
    # init_path: "C:/Users/admin/Neurips2025/MouseVsAI/mouse_vs_ai_windows/results/resnet_with_augmentation_RandomTrain_1/My Behavior/My Behavior-500007.pt"
    # init_path: "E:/Mouse.vs.AI/MouseAgent/results/nature_RandomTrain_5/My Behavior/My Behavior-205141.pt"
    init_path: "E:/Mouse.vs.AI/MouseAgent/results/nature_RandomTrain_8/My Behavior/My Behavior-249992.pt"
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 9e-5
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: nature_cnn
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    checkpoint_interval: 10000
    keep_checkpoints: 200
    max_steps: 500000
    summary_freq: 1000
    threaded: true
    # save_models: true
    # export_onnx: false